-- [III] JOIN : 2개 이상의 테이블을 연결하여 데이터를 검색하는 방법
SELECT * FROM EMP WHERE ENAME ='SCOTT'; --1행
SELECT * FROM DEPT;  -- 4행
-- CROSS JOIN(FROM 절이 테이블을 2개이상)
SELECT * FROM EMP, DEPT WHERE ENAME='SCOTT'; ---EMP의 1행 * DEPT의 4행 잘못됨

-- ▶1. EQUI JOIN : 공통필드 값이 일치되는 조건만 JOIN (많이 사용함)
SELECT * FROM EMP, DEPT WHERE ENAME='SCOTT' AND EMP.DEPTNO = DEPT.DEPTNO; 
SELECT * FROM EMP, DEPT WHERE  EMP.DEPTNO = DEPT.DEPTNO; 

SELECT EMPNO, ENAME, D.DEPTNO, DNAME, LOC --공통으로 존재하는 컬럼은 E 나 D를 지정해줘야 ERROR 없음
FROM EMP E, DEPT D 
WHERE  E.DEPTNO = D.DEPTNO;     ---EMP . DEPT는 인식 안됨

SELECT E.*, D.* 
FROM EMP E, DEPT D 
WHERE  E.DEPTNO = D.DEPTNO;     