-- [V] 시퀀스 : 순차번호 생성기. 인위적인 PK 사용용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1          --- 1부터 시작 (기본값 1)
    INCREMENT BY 1     ---  1씩 증가(기본값 1)
    MAXVALUE 9999      ---   최대값
    MINVALUE 1              ---  최소값
    NOCACHE                  
    NOCYCLE;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL;  --다음 순차번호 생성 
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; 

-- EX. FRIEND테이블(NO; 숫3-PK, NAME문20, TEL문20, ADDRESS문200, LAST_MODIFY날)
DROP SEQUENCE FRIEND_NO_SEQ;
CREATE SEQUENCE FRIEND_NO_SEQ MAXVALUE 999 NOCACHE NOCYCLE;

CREATE TABLE FRIEND(
    NO               NUMBER(3)          PRIMARY KEY,
    NAME          VARCHAR2(20)   NOT NULL,
    TEL             VARCHAR2(20)   UNIQUE,
    ADDRESS    VARCHAR2(200),
    LAST_MODIFY DATE   DEFAULT SYSDATE
);


INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_NO_SEQ.NEXTVAL, '홍길동', NULL, '관악구 실림동');
    
SELECT * FROM FRIEND;

INSERT INTO FRIEND 
    VALUES (FRIEND_NO_SEQ.NEXTVAL, '성춘향', '010-999-9999', '남원',SYSDATE);

